---
title: "Cleveland Heart Disease Prediction and Investigation"
author: Manny McGrail
output: html_document
date: "2023-11-22"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r, warning=FALSE}
# Note: 0 means no diagnosis, and then there proceeds to be a diagnosis score of 1, 2, 3, and 4 following that.
hd_data <- read.csv("C:/Users/super/Desktop/Coding Projects/Data Sets/heart-disease-cleveland.csv")
library(ggplot2)
library(caret)
library(rpart)
library(rpart.plot)
head(hd_data)

# I would like to note that I am looking into ways of improving this model. I am for now just using the rpart library (decision tree) to create this model. I originally tried a support vector machine and the model performance was sub-par, and I was determined to find a way to get the accuracy above atleast 65%, making our machine relatively good at predicting when considered there are four levels.
```

```{r, warning=FALSE}
# Data cleaning
hd_data$diagnosis <- as.factor(hd_data$diagnosis)
hd_data$sex <- as.factor(hd_data$sex)
hd_data$restecg <- as.factor(hd_data$restecg)
hd_data$exang <- as.factor(hd_data$exang)
hd_data$cp <- as.factor(hd_data$cp)
hd_data$fbs <- as.factor(hd_data$fbs)
hd_data$thal <- as.factor(hd_data$thal)

  
# Visualize many aspects of our data to get a full picture
ggplot(hd_data, aes(x = chol, y = age, color = diagnosis)) + 
  geom_point()

ggplot(hd_data, aes(x = chol)) +
  geom_histogram()

ggplot(hd_data, aes(x = oldpeak, y = thalach, color = diagnosis)) +
  geom_point()

ggplot(hd_data, aes(x = chol, y = diagnosis)) +
  geom_boxplot()

ggplot(hd_data, aes(x = thalach, y = diagnosis)) +
  geom_boxplot()

ggplot(hd_data, aes(x = oldpeak, y = diagnosis)) +
  geom_boxplot()

ggplot(hd_data, aes(x = age, y = diagnosis)) + 
  geom_boxplot()

ggplot(hd_data, aes(x = age, y = trestbps, color = diagnosis)) +
  geom_point()

ggplot(hd_data, aes(x = trestbps, y = diagnosis)) +
  geom_boxplot()

ggplot(hd_data, aes(x = diagnosis, fill = fbs)) +
  geom_bar()
```

```{r}
table(hd_data$diagnosis)
```

```{r}
set.seed(123)
(treeOne <- rpart(diagnosis ~., data = hd_data, cp = 0.001))
rpart.plot(treeOne)
```

```{r}
pred_labels <- predict(treeOne, hd_data, type = "class")
pred_labels[1:10]
```
```{r}
(my_table <- table(our_predictions = pred_labels, reality = hd_data$diagnosis))
```


```{r}
accuracy <- sum(diag(my_table)/sum(my_table))
print(accuracy)
```
